//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        public string TenMatHang { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public int MaMH { get; set; }
        public Nullable<int> MaLoai { get; set; }
    
        public virtual LoaiMH LoaiMH { get; set; }
    }
}
